// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjw6ZUaAadP088PgkoSug_t9OH0zcsrhM',
    appId: '1:330344270546:web:89b6e090fdc2b9cf17fb0b',
    messagingSenderId: '330344270546',
    projectId: 'socielmedia-65f3d',
    authDomain: 'socielmedia-65f3d.firebaseapp.com',
    storageBucket: 'socielmedia-65f3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTY4JhHu3XivIeGm4VoZgoOwpnA8gO_bM',
    appId: '1:330344270546:android:1ebb5b5c57e4d98117fb0b',
    messagingSenderId: '330344270546',
    projectId: 'socielmedia-65f3d',
    storageBucket: 'socielmedia-65f3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1X-QQFUcRgpZkwTWqLYtPYUkNCr6QfGU',
    appId: '1:330344270546:ios:cc0fd00bc00c7ef817fb0b',
    messagingSenderId: '330344270546',
    projectId: 'socielmedia-65f3d',
    storageBucket: 'socielmedia-65f3d.appspot.com',
    iosBundleId: 'com.example.socielmedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1X-QQFUcRgpZkwTWqLYtPYUkNCr6QfGU',
    appId: '1:330344270546:ios:e9d6d71ed4bd7de017fb0b',
    messagingSenderId: '330344270546',
    projectId: 'socielmedia-65f3d',
    storageBucket: 'socielmedia-65f3d.appspot.com',
    iosBundleId: 'com.example.socielmedia.RunnerTests',
  );
}
